---
title: "Untitled"
author: "Zimo Zhang"
date: "2024/5/30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("D://2024Capstone//data")
getwd()
```

```{r}
library(ggplot2)
library(viridis)
## Loading required package: viridisLite
library(broom)
## Warning: package 'broom' was built under R version 4.1.2
library(dplyr)
## 
## Attaching package: 'dplyr'
## The following objects are masked from 'package:stats':
## 
##     filter, lag
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
library(gt)
## Warning: package 'gt' was built under R version 4.1.2
library(formula.tools)
## Warning: package 'formula.tools' was built under R version 4.1.3
library(logger)
library(future.apply)
## Warning: package 'future.apply' was built under R version 4.1.3
## Loading required package: future
library(meta)
## Warning: package 'meta' was built under R version 4.1.3
## Loading 'meta' package (version 5.2-0).
## Type 'help(meta)' for a brief overview.
## Readers of 'Meta-Analysis with R (Use R!)' should install
## older version of 'meta' package: https://tinyurl.com/dt4y5drs
library(kableExtra)
## 
## Attaching package: 'kableExtra'
## The following object is masked from 'package:dplyr':
## 
##     group_rows

# Notebook settings
future::plan("multisession", workers = 4)
options(scipen = 999)
```


```{r}
# Example URL for utils.R
#url_utils <- "https://raw.githubusercontent.com/borenstein-lab/microbiome-metabolome-curated-data/main/scripts/data_organization/utils.R"
#download.file(url_utils, destfile = "utils.R")
#source("m-m//utils.R")

# Example URL for hmdb_utils.R
#url_hmdb_utils <- "https://raw.githubusercontent.com/borenstein-lab/microbiome-metabolome-curated-data/main/scripts/data_analysis/hmdb_utils.R"
#download.file(url_hmdb_utils, destfile = "hmdb_utils.R")
#source("m-m//hmdb_utils.R")

# Load utility scripts
source("D://2024Capstone//data//scripts//data_organization//utils.R")
## Loading required package: readr
## Warning: package 'readr' was built under R version 4.1.2
source("D://2024Capstone//data//scripts//data_analysis//hmdb_utils.R")
```

```{r}
load.all.datasets1 <- function(parent.folder = "processed_data") {
  # Get all processed datasets
  data.dirs <- list.dirs(file.path("D://2024Capstone//data//data", parent.folder))[-1]
  
  # Initialize table lists
  all.data <- list()
  all.data$data.dirs <- data.dirs
  all.data$metadata <- list()
  all.data$mtb <- list()
  all.data$mtb.map <- list()
  all.data$genera <- list()
  all.data$species <- list()
  all.data$genera.counts <- list()
  all.data$species.counts <- list()
  
  for (x in data.dirs) {
    # Create a temporary environment to hold all processed tables
    tmp.env <- new.env()
    dataset.name <- basename(x)
    
    # Load and save tables
    load(file.path(x, ".RData"), tmp.env)
    all.data$mtb[[dataset.name]] <- get('mtb', tmp.env) 
    all.data$mtb.map[[dataset.name]] <- get('mtb.map', tmp.env) 
    all.data$genera[[dataset.name]] <- get('genera', tmp.env) 
    all.data$metadata[[dataset.name]] <- get('metadata', tmp.env)
    if ("species" %in% ls(tmp.env)) all.data$species[[dataset.name]] <- get('species', tmp.env) 
    if ("genera.counts" %in% ls(tmp.env)) all.data$genera.counts[[dataset.name]] <- get('genera.counts', tmp.env) 
    if ("species.counts" %in% ls(tmp.env)) all.data$species.counts[[dataset.name]] <- get('species.counts', tmp.env) 
    
    # Clean up
    rm(tmp.env)
  }
  
  message("Datasets loaded successfully")
  return(all.data)
}
```

```{r}
all.data <- load.all.datasets1()
#parent.folder = "D://2024Capstone//data"

for(i in 1:length(all.data)) assign(names(all.data)[i], all.data[[i]])
#rm(all.data)

all.data$mtb.map
```
```{r}

datasets <- c("FRANZOSA_IBD_2019",
              "JACOBS_IBD_FAMILIES_2016",
              "iHMP_IBDMDB_2019")


```

```{r}
# If the file exists, it will be loaded instead of re-computed
file.lm.results.raw <- "scripts//data_analysis//linear_models_genus_metabolite.tsv"
file.rem.results <- "scripts//data_analysis//rem_results.tsv"
file.hmdb.data <- "scripts//data_analysis//hmdb_info.tsv"
file.cytoscape.network <- "scripts//data_analysis//cytoscape_network.tsv"
file.cytoscape.nodes <- "scripts//data_analysis//cytoscape_node_attributes.tsv"
```

```{r}
# Metabolite-dataset statistics
metabolites.per.dataset <- 
  get.metab.dataset.stats(mtb.map, datasets)

# Genera-dataset statistics
genera.dataset.stats <- 
  get.genera.dataset.stats(genera, datasets) %>%
  # Add averaged statistics (over datasets)
  group_by(Taxon) %>%
  mutate(Averaged.Taxon.Mean.Abundance = 
           weighted.mean(Taxon.Mean.Abundance, Dataset.N),
         Averaged.Taxon.Perc.of.Non.Zeros = 
           weighted.mean(Taxon.Perc.of.Non.Zeros, Dataset.N),
         N.Datasets = n_distinct(Dataset))
```
```{r}
mtb_map %>% select(where(is.numeric))
```

```{r}
genera.dataset.stats <- genera.dataset.stats %>%
  filter(Averaged.Taxon.Perc.of.Non.Zeros >= 25) %>%
  filter(Averaged.Taxon.Mean.Abundance >= 0.001)

# We additionally discard genera from individual datasets if they 
#  are mostly zero's there. See for example:
#  View(genera.dataset.stats %>% filter(grepl("g__Clostridioides",Taxon)))
genera.dataset.stats <- genera.dataset.stats %>%
  filter(Taxon.Perc.of.Non.Zeros >= 10) 

# And lastly discard ambiguous/unidentified genera
genera.dataset.stats <- genera.dataset.stats %>%
  filter(! grepl("g__$", Taxon))
```

```{r}
metabolites.per.dataset <- metabolites.per.dataset %>%
  filter(Type == "HMDB") %>%
  select(-Type)

# Also remove metabolites with constant values across cohort
is.constant <- apply(metabolites.per.dataset, MARGIN = 1, function(r) {
  # Get vector of values of a metabolite
  tmp <- mtb[[unname(r["Dataset"])]][,unname(r["Orig.Compound"])]
  
  # Return true if constant
  return(var(tmp, na.rm = TRUE) == 0)
})
metabolites.per.dataset <- metabolites.per.dataset[!is.constant,]
```

```{r}
common.pairs <- inner_join(genera.dataset.stats,
                           metabolites.per.dataset,
                           by = "Dataset") %>%
  relocate(Dataset, Dataset.N) %>%
  group_by(Taxon, Compound) %>%
  filter(n_distinct(Dataset) >= 3) %>% 
  mutate(Pair = paste(Compound, 
                      gsub(".*;f__","f__",Taxon),
                      sep = "~"))

# Print statistics
paste(n_distinct(common.pairs$Pair), 
      "unique genus-metabolite pairs will be analyzed")
paste("These include", n_distinct(common.pairs$Compound), 
      "metabolites and", n_distinct(common.pairs$Taxon), "genera")
```

```{r}
# Metadata fields to include (if exist)
metadata.fields <- c("Sample", 
                     "Age", 
                     "Gender", 
                     "Subject", 
                     "Study.Group", 
                     "BMI")

data.for.lm <- lapply(datasets, function(d) {
  log_info(sprintf("Preparing data for %s", d))
  
  # For compactness we fetch only relevant genera and metabolites,
  #  included in our pairs of interest.
  
  # Get relevant genera
  relevant.genera <- common.pairs %>% 
    filter(Dataset == d) %>% 
    pull(Taxon) %>% 
    unique()
  relevant.genera <- genera[[d]] %>%
    select("Sample", any_of(relevant.genera))
  
  # Arcsine square root relative abundance values
  relevant.genera[-1] <- asin(sqrt(relevant.genera[-1]))
  
  # Get relevant metabolites
  relevant.cmpd <- common.pairs %>% 
    filter(Dataset == d) %>% 
    pull(Orig.Compound) %>% 
    unique()
  relevant.cmpd <- mtb[[d]] %>% 
    select("Sample", any_of(relevant.cmpd))
  
  # Log scale metabolomics (unless already scaled)
  if (min(relevant.cmpd %>% 
            summarise(across(-1, min, na.rm = T)), 
          na.rm = T) >= 0)
    relevant.cmpd[-1] <- log1p(relevant.cmpd[-1])
  
  # Combine all variables in one table
  tmp <- metadata[[d]] %>% 
    select(any_of(metadata.fields)) %>%
    mutate(Sample = as.character(Sample)) %>%
    left_join(relevant.cmpd, by = "Sample") %>%
    left_join(relevant.genera, by = "Sample")
  
  return(tmp)
})
names(data.for.lm) <- datasets
```

```{r}
data.for.lm$FRANZOSA_IBD_2019
```


```{r}
# Iterate over datasets (in parallel - future_lapply)
  lm.results <- future_lapply(datasets, function(d) {
    # Example: d = datasets[10] 
    print(sprintf("Fitting LM models for genus-metabolite pairs in dataset: %s", d))
    
    # Get dataset data and list of pairs to check
    tmp <- data.for.lm[[d]]
    pairs.to.check <- common.pairs %>% 
      filter(Dataset == d) 
    
    # For each pair - fit a linear model and record results
    # Example: r = unlist(pairs.to.check[11634,])
    lms <- data.frame(
      t(apply(pairs.to.check, MARGIN = 1, function(r) { 
        
        metab.in.pair <- unname(r["Orig.Compound"])
        genus.in.pair <- unname(r["Taxon"])
        tmp.data.for.lm <- tmp %>%
          select(all_of(c(metab.in.pair, genus.in.pair)), 
                 any_of(metadata.fields)) %>%
          rename("Compound" = 1, "Taxon" = 2) %>% 
          select(where(~sum(!is.na(.x)) > 0))
        
        # Generate the regression formula, 
        #  add study.group covariate if available
        lm.formula <- as.formula("Compound ~ Taxon")
        if ("Study.Group" %in% names(tmp.data.for.lm))
          lm.formula <- add.var.to.formula(lm.formula, "Study.Group")
        
        # Fit the model
        lm.model <- lm(lm.formula, data = tmp.data.for.lm)
        lm.model.sum <- summary(lm.model)
        
        # Get the semi-partial correlation between genus 
        #  abundance and metabolite using Equation 2 from
        #  Aloe and Becker, 2012 (cited above).
        r.sp <- 
          (lm.model.sum$coefficients["Taxon", "t value"] * 
             sqrt(1 - lm.model.sum$r.squared)) /
          (sqrt(nrow(tmp.data.for.lm) - 
                  (length(lm.formula)-1) - 1))
          
        # Fit a second model that also controls for Age, 
        #  BMI and Gender when available
        lm.formula2 <- lm.formula
        if ("Age" %in% names(tmp.data.for.lm))
          lm.formula2 <- add.var.to.formula(lm.formula2, "Age")
        if ("BMI" %in% names(tmp.data.for.lm))
          lm.formula2 <- add.var.to.formula(lm.formula2, "BMI")
        if ("Gender" %in% names(tmp.data.for.lm))
          lm.formula2 <- add.var.to.formula(lm.formula2, "Gender")
        lm.model2 <- lm(lm.formula2, data = tmp.data.for.lm)
        lm.model.sum2 <- summary(lm.model2)
        
        c("Dataset" = d,
          "Taxon" = genus.in.pair,
          "Orig.Compound" = metab.in.pair,
          "LM.Formula" = as.character(lm.formula),
          "LM.Adj.R2" = lm.model.sum$adj.r.squared,
          # Extract the F-statistic P value from LM model summary (goodness of fit measure)
          "LM.PVal" = unname(glance(lm.model.sum)$p.value),
          # Extract the coefficient and its P value for the taxon variable in the regression
          "LM.Taxon.Coef" = lm.model.sum$coefficients["Taxon", "Estimate"],
          "LM.Taxon.PVal" = lm.model.sum$coefficients["Taxon", "Pr(>|t|)"],
          "LM.Taxon.r.sp" = r.sp,
          "LM2.Formula" = as.character(lm.formula2),
          "LM2.Adj.R2" = lm.model.sum2$adj.r.squared,
          # Extract the F-statistic P value from LM model summary (goodness of fit measure)
          "LM2.PVal" = unname(glance(lm.model.sum2)$p.value),
          # Extract the coefficient and its P value for the taxon variable in the regression
          "LM2.Taxon.Coef" = lm.model.sum2$coefficients["Taxon", "Estimate"],
          "LM2.Taxon.PVal" = lm.model.sum2$coefficients["Taxon", "Pr(>|t|)"])
    })))
    
    # Sanity
    sprintf("Sanity: fitted %i/%i requested models", nrow(pairs.to.check), nrow(lms))
    
    # Convert numbers back to numeric
    lms <- lms %>% mutate_at(c("LM.Adj.R2","LM2.Adj.R2",
                               "LM.Taxon.PVal","LM2.Taxon.PVal",
                               "LM.Taxon.Coef","LM2.Taxon.Coef",
                               "LM.PVal","LM2.PVal","LM.Taxon.r.sp"), 
                             as.numeric)
    
    # Apply FDR
    lms$LM.Taxon.FDR <- p.adjust(lms$LM.Taxon.PVal, method = "fdr")
    lms$LM2.Taxon.FDR <- p.adjust(lms$LM2.Taxon.PVal, method = "fdr")
    
    n.models <- nrow(lms)
    n.sig.models <- sum(lms$LM.Taxon.FDR < 0.05)
    sprintf("Of %i LM models, %i (%.2f%%) resulted in significant associations", 
            n.models, n.sig.models, 100*n.sig.models/n.models)
    
    return(lms)
  }, future.packages = c("logger", "formula.tools", "broom"))
  
  # Merge into one big table
  lm.results <- bind_rows(lm.results)
  
  # Add details per pair
  lm.results <- lm.results %>%
    left_join(common.pairs, by = c("Dataset","Taxon","Orig.Compound"))
  
  # Per dataset, take only the best model per genus-metabolite pair
  # (for cases where a compound was measured more than once, for example when running multiple MS methods)
  lm.results <- lm.results %>%
    group_by(Dataset, Pair) %>%
    slice_min(order_by = LM.Taxon.FDR, with_ties = FALSE) %>% 
    ungroup()
  
  write_delim(lm.results, file = file.lm.results.raw, delim = "\t")
```

```{r}
paste0("A total of ", nrow(lm.results), " linear models were fitted")
n.lm.signif <- lm.results %>% filter(LM.Taxon.FDR < 0.05) %>% nrow()
paste0(n.lm.signif, " (", round(100*n.lm.signif/nrow(lm.results),2), "%) of which had a FDR<0.05 for the genus coefficient")
```

```{r}
 hmdb.ids <- unique(lm.results$Compound)
  hmdb.data <- get.hmdb.data.by.ids(hmdb.ids) 
  hmdb.data <- hmdb.data %>% rename(Compound = HMDB)
  
  # Manually fill-in some missing KEGG's
  hmdb.data$KEGG[hmdb.data$Compound == "HMDB0000043"] <- "D07523"
  hmdb.data$KEGG[hmdb.data$Compound == "HMDB0000613"] <- "C21593"
  hmdb.data$KEGG[hmdb.data$Compound == "HMDB0004704"] <- "C14828"
   
  # ... and some missing classes
  hmdb.data$HMDB.Class[hmdb.data$Compound == "HMDB0000357"] <- 
    "Hydroxy acids and derivatives"
  hmdb.data$HMDB.Super.Class[hmdb.data$Compound == "HMDB0000357"] <- 
    "Organic acids and derivatives"
  hmdb.data$HMDB.Class[hmdb.data$Compound == "METPA0797"] <- 
    "Carboxylic acids and derivatives"
  hmdb.data$HMDB.Super.Class[hmdb.data$Compound == "METPA0797"] <- 
    "Amino acids, peptides, and analogues"
  
  write_delim(hmdb.data, file = file.hmdb.data, delim = "\t")
```


```{r}
not.assoc.label <- "Not associated"
pos.assoc.label <- "Positively associated"
neg.assoc.label <- "Negatively associated"
cat.colors <- c("lightgrey", "#1CA59F", "#C05475")
names(cat.colors) <- c(not.assoc.label, pos.assoc.label, neg.assoc.label)

# Choose taxa and metabolites that are most associated
taxa.to.plot <- lm.results %>%
 group_by(Taxon) %>%
 summarise(N = n(), N.Signif = sum(LM.Taxon.FDR < 0.05), .groups = "drop") %>%
 slice_max(order_by = N.Signif, n = 15) %>%
 mutate(Genus = gsub(".*;g__","g__",Taxon)) %>%
 pull(Genus)

mtb.to.plot <- lm.results %>%
 group_by(Compound) %>%
 summarise(N = n(), N.Signif = sum(LM.Taxon.FDR < 0.05), .groups = "drop") %>%
 slice_max(order_by = N.Signif, n = 25) %>%
 pull(Compound)

# Plot data
tmp <- lm.results %>%
  ungroup() %>%
  mutate(Category = ifelse(LM.Taxon.FDR > 0.05, 
                           not.assoc.label,
                           ifelse(LM.Taxon.Coef > 0, 
                                  pos.assoc.label, 
                                  neg.assoc.label))) %>%
  select(Taxon, Compound, Dataset, Category) %>%
  mutate(Value = 1) %>%
  mutate(Genus = gsub(".*;g__","g__",Taxon)) %>%
  filter(Genus %in% taxa.to.plot) %>%
  filter(Compound %in% mtb.to.plot) %>%
  left_join(hmdb.data, by = "Compound") %>%
  mutate(Compound = factor(Compound, levels = mtb.to.plot)) %>%
  mutate(Genus = factor(Genus, levels = taxa.to.plot))


ggplot(tmp, aes(x = "", y = Value, fill = Category)) +
  geom_bar(stat = "identity", width = 1, color = "black", size = 0.6, position = "fill") +
  coord_polar("y", start = 0) +
  theme_void() +
  scale_fill_manual(values = cat.colors) +
  facet_grid(Genus ~ Compound, switch = "both") +
  theme(legend.position = "top") +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_text(angle = 90, size = 10, hjust = 1, vjust = 0.55)) +
  theme(strip.text.y.left = element_text(size = 10, hjust = 1, angle = 0)) +
  theme(panel.spacing = unit(0, "lines")) +
  theme(legend.title = element_blank()) +
  theme(legend.text = element_text(size = 12))
```

